# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  do_everything:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os }}

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '>=22'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: codecov/codecov-action@v5.4.3
      if: "!contains(github.event.head_commit.message, 'skip test')"
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
